- name: Arch Linux AUR-only desktop setup
  hosts: localhost
  become: true
  vars:
    user_name: xmegaherox11

  tasks:
    - name: Enable multilib repository and uncomment mirrorlist
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        marker: "# {mark} MULTILIB REPO"

    - name: Update package databases and system
      pacman:
        update_cache: yes
        upgrade: yes
    
    - name: Force refresh package databases
      pacman:
        update_cache: yes
        force: yes

    - name: Set GRUB timeout to 0 for immediate boot
      become: yes
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: 'GRUB_TIMEOUT=0'
        create: yes
      notify: Update grub config
    
    - name: Install Hyprland Stuff
      pacman:
        name:
          - hyprland # hyprland
          - neovim # text editor
          - kitty # terminal
          - rofi # app launcher
          - dolphin # file browser
          - hyprpaper # wallpaper
          - hyprlock # lockscreen
          - waybar # top bar
          - nwg-look # theme for gtk apps
          - swaync # notification tool
          - hypridle # idle
          - hyprcursor # cursor
          - hyprsunset # blue light filter
          - pipewire # screen sharing
          - xdg-desktop-portal-hyprland # screen sharing
          - starship # terminal theming
          - ttf-cascadia-code-nerd # font
          - kdegraphics-thumbnailers # thumbnails in dolphin
        state: present

    - name: Clone Dotfiles Git Repo
      ansible.builtin.git:
        repo: 'https://github.com/typecraft-dev/dotfiles.git'
        dest: "/home/{{ user_name }}/dotfile"
        clone: yes
        force: yes

    - name: Install Drivers
      pacman:
        name:
          - libarchive
          - 
          - cups
          - base-devel
          - git
          - ansible
          - mesa
          - lib32-mesa
          - vulkan-radeon
          - lib32-vulkan-radeon
          - libva-mesa-driver
          - lib32-libva-mesa-driver
          - libva-utils

    - name: Install Software
      pacman:
        name:
         - rclone
         - gimp
         - vlc
         - discord
         - libreoffice-fresh
         - nextcloud-client
         - lutris
         - bitwarden
         - firefox
         - steam
         - chromium
        state: present

    - name: Check if yay is already installed
      register: yay_installed
      changed_when: false
      failed_when: false
      ansible.builtin.command: which yay
    
    - name: Clone yay from AUR
      become: true
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "/home/{{ user_name }}/yay"
        clone: yes
      when: yay_installed.rc != 0
    
    - name: Ensure yay directory is owned by the user
      become: true
      file:
        path: "/home/{{ user_name }}/yay"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: yay_installed.rc != 0
    
    - name: Build and install yay
      become: false
      become_user: "{{ user_name }}"
      shell: |
        cd /home/{{ user_name }}/yay
        makepkg -si --noconfirm
      environment:
        BUILDDIR: "/home/{{ user_name }}/yay"
      when: yay_installed.rc != 0

    - name: Ensure .bash_profile contains Hyprland autostart
      become: true
      lineinfile:
        path: "/home/{{ user_name }}/.bash_profile"
        line: '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec Hyprland'
        create: yes
        state: present

    - name: Create Wayland session file for Hyprland
      become: true
      copy:
        dest: /usr/share/wayland-sessions/hyprland.desktop
        content: |
          [Desktop Entry]
          Name=Hyprland
          Comment=An intelligent dynamic tiling Wayland compositor
          Exec=Hyprland
          Type=Application
          DesktopNames=Hyprland
        mode: '0644'

    - name: Set Hyprland keyboard layout to 'de'
      ansible.builtin.lineinfile:
        path: "/home/{{user_name}}/.config/hypr/hyprland.conf"
        regexp: '^input:kb_layout\s*='
        line: 'input:kb_layout = de'
        create: yes
        backup: yes

    - name: Ensure background_opacity is set to 0.9 in kitty.conf
      ansible.builtin.lineinfile:
        path: "/home/{{user_name}}/.config/kitty/kitty.conf"
        regexp: '^background_opacity\s+'
        line: 'background_opacity 0.9'
        insertafter: EOF
        state: present
        create: yes
    
    - name: Ensure starship init is in .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ user_name }}/.bashrc"
        line: 'eval "$(starship init bash)"'
        insertafter: EOF
        state: present
        create: yes
    
    - name: Set font_family in kitty.conf to Caskaydia Cove Nerd Font
      ansible.builtin.lineinfile:
        path: "/home/{{user_name}}/.config/kitty/kitty.conf"
        regexp: '^font_family\s+'
        line: 'font_family Caskaydia Cove Nerd Font'
        create: yes
    
 #   - name: Install AUR packages with yay
 #     become: false
 #     become_user: "{{ user_name }}"
 #     command: yay -S --noconfirm iwmenu-git bzmenu-git hyprsysteminfo hyprpicker-git catpuccin-gtk-theme-mocha hyprshot wireplumbe jellyfin-media-player finamp 

    - name: Set the system time zone to Berlin
      command:
        cmd: timedatectl set-timezone Europe/Berlin

    - name: Set the system keyboard layout to German
      command:
        cmd: localectl set-keymap de

    - name: Check if omega folder exists
      stat:
        path: "/home/{{ user_name }}/omega"
      register: omega_folder

    - name: Ensure unzip is installed
      package:
        name: unzip
        state: present
      when: not omega_folder.stat.exists

    - name: Download omega linux-x64.zip using curl
      shell: |
        curl -L https://github.com/duelists-unite/omega-releases/releases/download/Latest/linux-x64.zip -o /tmp/linux-x64.zip
      args:
        creates: /tmp/linux-x64.zip
      when: not omega_folder.stat.exists

    - name: Unzip omega archive into user home directory
      unarchive:
        src: /tmp/linux-x64.zip
        dest: "/home/{{ user_name }}/omega"
        remote_src: yes
        creates: "/home/{{ user_name }}/omega"
      become: yes
      become_user: "{{ user_name }}"
      when: not omega_folder.stat.exists
        
  handlers:
    - name: Update grub config
      become: yes
      command: grub-mkconfig -o /boot/grub/grub.cfg
