- name: Arch Linux AUR-only desktop setup
  hosts: localhost
  become: true
  vars:
    user_name: xmegaherox11

  tasks:
    - name: Enable multilib repository and uncomment mirrorlist
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        marker: "# {mark} MULTILIB REPO"

    - name: Update package databases and system
      pacman:
        update_cache: yes
        upgrade: yes
        force: yes

    - name: disable need for password for pacman to allow yay install
      lineinfile:
        path: /etc/sudoers.d/temp_allow_no_pswd_pacman
        state: present
        line: "ALL ALL=NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: yes

    - name: git clone yay-bin repo in to /tmp
      become: no
      git:
        repo: 'https://aur.archlinux.org/yay-bin.git'
        dest: /tmp/yay-bin
        clone: yes

    - name: Install yay using makepkg
      become: no
      shell: makepkg -si --noconfirm
      args:
        chdir: /tmp/yay-bin

    - name: set yay options to cleanafter package installation
      become: no
      shell: yay -Y --answerclean All --removemake --cleanafter --save
      args:
        executable: /usr/bin/bash

    - name: Install AUR packages
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - stow
        - nano
        - rclone
        - gimp
        - vlc
        #- ryujinx
        - pcsx2
        - epsxe
        - mgba
        - snes9x
        - rpcs3
        - mupen64plus
        - dolphin-emu
        - fceux
        - steam-rom-manager-bin
        - minecraft-launcher
        - libreoffice-fresh
        - nextcloud-client
        - lutris
        - bitwarden
        - steam
        - jellyfin-media-player
        - finamp-bin
        - vesktop
        #- ygo-omega
        - firefox
        - htop 
        - libarchive
        - pipewire # audio
        - pipewire-pulse # audio
        - blueman # bluetooth
        - bluez # bluetooth
        - bluez-utils # bluetooth
        - brightnessctl # brightness
        - cups
        - base-devel
        - git
        - ansible
        - mesa
        - lib32-mesa
        - vulkan-radeon
        - lib32-vulkan-radeon
        - libva-mesa-driver
        - lib32-libva-mesa-driver
        - libva-utils
        - tmux
        - hyprland # hyprland
        - neovim # text editor
        - kitty # terminal
        - pokemon-colorscripts-git
        - wofi # app launcher      
        - thunar # file browser
        - thunar-archive-plugin  # file browser archive
        - hyprpaper # wallpaper
        - hyprlock # lockscreen
        - waybar # top bar
        - nwg-look # theme for gtk apps
        - swaync # notification tool
        - hypridle # idle
        - hyprcursor # cursor
        - hyprsunset # blue light filter
        - pipewire # screen sharing
        - xdg-desktop-portal-hyprland # screen sharing
        - starship # terminal theming
        - ttf-cascadia-code-nerd # font
        - kdegraphics-thumbnailers # thumbnails in dolphin
        - bibata-cursor-theme
      loop_control:
        label: "{{ item }}"

    - name: Find all stow package directories in ./dotfiles
      find:
        paths: "{{ playbook_dir }}/dotfiles"
        file_type: directory
        depth: 1
      register: stow_packages
    
    - name: Stow each dotfiles package to $HOME
      stow:
        state: present
        package: "{{ item.path | basename }}"
        dir: "{{ playbook_dir }}/dotfiles"
      loop: "{{ stow_packages.files }}"

