- name: Arch Linux AUR-only desktop setup
  hosts: localhost
  become: true
  vars:
    user_name: xmegaherox11

  tasks:
    - name: Enable multilib repository and uncomment mirrorlist
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        marker: "# {mark} MULTILIB REPO"

    - name: Update package databases and system
      pacman:
        update_cache: yes
        upgrade: yes
    
    - name: Force refresh package databases
      pacman:
        update_cache: yes
        force: yes

    - name: disable need for password for pacman to allow yay install
      lineinfile:
        path: /etc/sudoers.d/temp_allow_no_pswd_pacman
        state: present
        line: "ALL ALL=NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: yes

    - name: git clone yay-bin repo in to /tmp
      become: no
      git:
        repo: 'https://aur.archlinux.org/yay-bin.git'
        dest: /tmp/yay-bin
        clone: yes

    - name: Install yay using makepkg
      become: no
      shell: makepkg -si --noconfirm
      args:
        chdir: /tmp/yay-bin

    - name: set yay options to cleanafter package installation
      become: no
      shell: yay -Y --answerclean All --removemake --cleanafter --save
      args:
        executable: /usr/bin/bash




    - name: Install AUR packages
          yay:
            name: "{{ item }}"
            state: present
          loop:
            - rclone
            - gimp
            - vlc
            - libreoffice-fresh
            - nextcloud-client
            - lutris
            - bitwarden
            - steam
            - jellyfin-media-player
            - finamp
            - vesktop
            #- ygo-omega
            - firefox
            - htop 
            - libarchive
            - pipewire # audio
            - pipewire-pulse # audio
            - blueman # bluetooth
            - bluez # bluetooth
            - bluez-utils # bluetooth
            - brightnessctl # brightness
            - cups
            - base-devel
            - git
            - ansible
            - mesa
            - lib32-mesa
            - vulkan-radeon
            - lib32-vulkan-radeon
            - libva-mesa-driver
            - lib32-libva-mesa-driver
            - libva-utils
            - hyprland # hyprland
            - neovim # text editor
            - kitty # terminal
            - rofi # app launcher      
            - thunar # file browser
            - thunar-archive-plugin  # file browser archive
            - hyprpaper # wallpaper
            - hyprlock # lockscreen
            - waybar # top bar
            - nwg-look # theme for gtk apps
            - swaync # notification tool
            - hypridle # idle
            - hyprcursor # cursor
            - hyprsunset # blue light filter
            - pipewire # screen sharing
            - xdg-desktop-portal-hyprland # screen sharing
            - starship # terminal theming
            - ttf-cascadia-code-nerd # font
            - kdegraphics-thumbnailers # thumbnails in dolphin
          loop_control:
            label: "{{ item }}"

































        

    - name: Ensure .bash_profile contains Hyprland autostart
      become: true
      lineinfile:
        path: "/home/{{ user_name }}/.bash_profile"
        line: '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec Hyprland'
        create: yes
        state: present
    
    - name: Remove 'autogenerated = 1' from Hyprland config
      ansible.builtin.lineinfile:
        path: "/home/{{ user_name }}/.config/hypr/hyprland.conf"
        regexp: '^\s*autogenerated\s*=\s*1\s*$'
        state: absent
        backup: yes

    - name: Set Hyprland keyboard layout to 'de'
      ansible.builtin.lineinfile:
        path: "/home/{{user_name}}/.config/hypr/hyprland.conf"
        regexp: '^input:kb_layout\s*='
        line: 'input:kb_layout = de'
        create: yes
        backup: yes

    - name: Ensure background_opacity is set to 0.9 in kitty.conf
      ansible.builtin.lineinfile:
        path: "/home/{{user_name}}/.config/kitty/kitty.conf"
        regexp: '^background_opacity\s+'
        line: 'background_opacity 0.9'
        insertafter: EOF
        state: present
        create: yes
    
    - name: Set font_family in kitty.conf to Caskaydia Cove Nerd Font
      ansible.builtin.lineinfile:
        path: "/home/{{user_name}}/.config/kitty/kitty.conf"
        regexp: '^font_family\s+'
        line: 'font_family Caskaydia Cove Nerd Font'
        create: yes

    - name: Set the system time zone to Berlin
      command:
        cmd: timedatectl set-timezone Europe/Berlin

    - name: Set the system keyboard layout to German
      command:
        cmd: localectl set-keymap de
